apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator-replica
  labels:
    app: citus-coordinator-replica
    component: citus
spec:
  selector:
    app: citus-coordinator-replica
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
  - port: 6432
    name: pgbouncer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-coordinator-replica
spec:
  selector:
    matchLabels:
      app: citus-coordinator-replica
  serviceName: citus-coordinator-replica
  replicas: 2
  template:
    metadata:
      labels:
        app: citus-coordinator-replica
        component: citus
    spec:
      securityContext:
        runAsUser: 999
        supplementalGroups: [999,1000]
        fsGroup: 999

      initContainers:
      - name: pg-basebackup
        image: citusdata/citus:latest
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql/data
        - name: citus-cert
          mountPath: "/etc/citus-cert"
          readOnly: true
        command:
        - sh
        - -c
        - |
          if [ -z "$(ls -A $PGDATA)" ]; then
              echo "Running pg_basebackup to catch up replication server...";
              pg_basebackup -R -h citus-coordinator -D $PGDATA -P -U postgres;
              chown -R postgres:postgres $PGDATA;
          else
              echo "Skipping pg_basebackup because $PGDATA is not empty";
          fi
          psql 'host=citus-coordinator user=postgres' -c "select pg_create_physical_replication_slot('$(echo $HOSTNAME | tr -dc '[:alnum:]')');"

      containers:
      - name: postgres
        image: citusdata/citus:latest
        command:
        - sh
        - -c
        - >
            postgres -c ssl=on -c ssl_cert_file=/etc/citus-cert/tls.crt -c ssl_key_file=/etc/citus-cert/tls.key -c primary_conninfo='host=citus-coordinator user=postgres' -c primary_slot_name=$(echo $HOSTNAME | tr -dc '[:alnum:]')
        ports:
        - containerPort: 5432
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql/data
        - name: citus-cert
          mountPath: "/etc/citus-cert"
          readOnly: true
        livenessProbe:
          exec:
            command:
              - 'pg_isready'
              - '-U'
              - 'postgres'
              - '--timeout=5'
              - '--quiet'
          initialDelaySeconds: 60

      - name: pgbouncer
        image: bitnami/pgbouncer:latest
        ports:
        - containerPort: 6432
        env:
        - name: POSTGRESQL_HOST
          value: localhost
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: password
        - name: PGBOUNCER_AUTH_TYPE
          value: trust
        - name: PGBOUNCER_CLIENT_TLS_SSLMODE
          value: require
        - name: PGBOUNCER_CLIENT_TLS_CERT_FILE
          value: /etc/citus-cert/tls.crt
        - name: PGBOUNCER_CLIENT_TLS_KEY_FILE
          value: /etc/citus-cert/tls.key
        volumeMounts:
        - name: citus-cert
          mountPath: "/etc/citus-cert"
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
      volumes:
      - name: citus-cert
        secret:
          secretName: citus-cert
          defaultMode: 0440

  volumeClaimTemplates:
  - metadata:
      name: storage
      labels:
        app: citus-coordinator-replica
        component: citus
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
