apiVersion: v1
kind: Service
metadata:
  name: citus-worker
  labels:
    app: citus-worker
    component: citus
spec:
  selector:
    app: citus-worker
  clusterIP: None
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-worker
spec:
  selector:
    matchLabels:
      app: citus-worker
  serviceName: citus-worker
  replicas: 3
  template:
    metadata:
      labels:
        app: citus-worker
        component: citus
    spec:
      containers:
      - name: citus-worker
        image: registry.localhost:43051/postgres-citus:latest
        lifecycle:
          postStart:
            exec:
              command:
                - timeout
                - 5m
                - sh
                - -c
                - >
                   until pg_isready -U postgres --timeout=5 --quiet; do sleep 2; done;
                   psql -h citus-coordinator -U postgres -c "SELECT * from master_add_node('${HOSTNAME}.citus-worker.default.svc.cluster.local', 5432);"
        ports:
        - containerPort: 5432
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
              - 'pg_isready'
              - '-U'
              - 'postgres'
              - '--timeout=5'
              - '--quiet'
          initialDelaySeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: storage
      labels:
        app: citus-worker
        component: citus
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
