apiVersion: v1
kind: Service
metadata:
  name: citus-worker
  labels:
    app: citus-worker
    component: citus
spec:
  selector:
    app: citus-worker
  clusterIP: None
  ports:
  - port: 6432
    name: pgbouncer
  - port: 5432
    name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-worker
spec:
  selector:
    matchLabels:
      app: citus-worker
  serviceName: citus-worker
  replicas: 3
  template:
    metadata:
      labels:
        app: citus-worker
        component: citus
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: postgres
        image: citusdata/citus:latest
        args: ['postgres', '-c', 'ssl=on', '-c', 'ssl_cert_file=/etc/citus-cert/tls.crt', '-c', 'ssl_key_file=/etc/citus-cert/tls.key']
        lifecycle:
          postStart:
            exec:
              command:
                - timeout
                - 5m
                - sh
                - -c
                - >
                   until pg_isready -U postgres --timeout=5 --quiet; do sleep 2; done;
                   psql 'host=citus-coordinator user=postgres' -c "SELECT * from citus_add_node('${HOSTNAME}.citus-worker.default.svc.cluster.local', 6432);"
        ports:
        - containerPort: 5432
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql/data
        - name: citus-cert
          mountPath: "/etc/citus-cert"
          readOnly: true

        livenessProbe:
          exec:
            command:
              - 'pg_isready'
              - '-U'
              - 'postgres'
              - '--timeout=5'
              - '--quiet'
          initialDelaySeconds: 60

      - name: pgbouncer
        image: bitnami/pgbouncer:latest
        ports:
        - containerPort: 6432
        env:
        - name: POSTGRESQL_HOST
          value: localhost
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: password
        - name: PGBOUNCER_AUTH_TYPE
          value: trust
        - name: PGBOUNCER_CLIENT_TLS_SSLMODE
          value: require
        - name: PGBOUNCER_CLIENT_TLS_CERT_FILE
          value: /etc/citus-cert/tls.crt
        - name: PGBOUNCER_CLIENT_TLS_KEY_FILE
          value: /etc/citus-cert/tls.key
        volumeMounts:
        - name: citus-cert
          mountPath: "/etc/citus-cert"
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
      volumes:
      - name: citus-cert
        secret:
          secretName: citus-cert
          defaultMode: 0440

  volumeClaimTemplates:
  - metadata:
      name: storage
      labels:
        app: citus-worker
        component: citus
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
